### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by openhex-1337** [hoplik/Firehose-Finder#20]
If possible, please support Linux

**Comment by hoplik** [comment]
The whole project is written in C# in Visual Studio on Windows Forms. It would be irrational to completely migrate it to Linux. If you specify what kind of functionality you need, then i can try to implement it as a separate project.

**Comment by openhex-1337** [comment]
Thank you for your interest. This is a similar project programmed in Python. If it is possible to create a graphical interface on Linux, it would be great. 
https://github.com/bkerler/edl

**Comment by openhex-1337** [comment]
Thanks and good luck

**Comment by bkerler** [comment]
There are major changes right now being prepared for edl, including fhparse. QC has changed quite a lot of things and require me to fix those first in order to make edl work. After those things have been fixed, a gui is currently planned.

**Comment by hoplik** [comment]
Seems full completed
