### ISSUE TITLE
Add QCS2290

### ISSUE THREAD

**Issue by RenateUSB** [hoplik/Firehose-Finder#31]
SoC: Qualcomm QCS2290
Mfg: Onyx
Model: Poke5

HWID: 001860e100000000, QC: 001860e1, OEM: 0000, Model: 0000
Hash: d40eee56f3194665-574109a39267724a-e7944134cd53cb76-7e293d3c40497955-bc8a4519ff992b03-1fadc6355015ac87

No known loader.
I presume that the hash is a Qualcomm factory hash since there are a bunch of references.
I've never seen any loader for that hash so I can't say what the root cert is.

**Comment by hoplik** [comment]
Thank you. I will add the IDs to the database. Maybe someone will find a suitable programmer. About hash sum of the root certificate. You're right. The manufacturer writes the hash sum of the root certificate to the processor's internal memory. When trying to load the programmer, the processor compares the hash from memory with the hash of the root certificate of the programmer (there is usually a chain of three certificates). If there is a discrepancy, the download stops.

**Comment by hoplik** [comment]
Added
