### ISSUE TITLE
Cat s62 pro Firehose file

### ISSUE THREAD

**Issue by Denali007** [hoplik/Firehose-Finder#33]
Hey, 
new to github
I have a s62 pro. that is stuck in edl mode. to get it out i need to flash new firmware but i cant seem to find any firehose roms
Only ota roms. i have one extracted to images with payload dumper.

the phone has a sdm660 cpu

Binary build date: Jun 25 2019 @ 03:16:15
QSAHARASERVER CALLED LIKE THIS: 'QSaharaServer.ex'Current working dir: C:\Users\denal\AppData\Local\Apps\2.0\K3E227G6.W09\AXZNWD9P.8NR\fire..tion_0000000000000000_0017.000c_deeceb71553d2ede
Sahara mappings:
2: amss.mbn
6: apps.mbn
8: dsp1.mbn
10: dbl.mbn
11: osbl.mbn
12: dsp2.mbn
16: efs1.mbn
17: efs2.mbn
20: efs3.mbn
21: sbl1.mbn
22: sbl2.mbn
23: rpm.mbn
25: tz.mbn
28: dsp3.mbn
29: acdb.mbn
30: wdt.mbn
31: mba.mbn

22:52:13: Sahara protocol completed

Done.
Received S/N CPU - 52805249
HWID - 0008C0E123243732
OEM_PK_HASH (64) - EE43AB11D0CA65C9DE6F717134DAF0819B9610FA36C5AD94A484520EB7708836
SBL SW Ver. - 00000000

**Comment by hoplik** [comment]
> Only ota roms

Hi,
I have never met any programmers in ota. There is only an update of a part of the system components or programs. It is carried out with the system running and the programer is not needed for this. Therefore, you either need to look for the full firmware, either in the service, or a hack.
