### ISSUE TITLE
Reference table of all loaders

### ISSUE THREAD

**Issue by RenateUSB** [hoplik/Firehose-Finder#36]
Here is a reference table of Firehose loaders available on two sites.
You can search by PK hash or file MD5 to locate a loader.
This table is copyright, but feel free to **link** it in README.md if you like.
[http://www.temblast.com/ref/loaders.htm](http://www.temblast.com/ref/loaders.htm)
It should be updated regularly.

**Comment by hoplik** [comment]
Thank you for your work. Added to the readme.
===
Just in case, the latest (up-to-date) version of identifiers (https://github.com/hoplik/Firehose-Finder/blob/master/ForFilter.xml) and links to programmers (https://github.com/hoplik/Firehose-Finder/blob/master/ForFound.xml) are located in the FhF program files in xml format for ease of further processing.
